trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --legacy-peer-deps'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'npm run build'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'public'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build files to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Portfolio'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'